// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAneAQm0vFQsTnssEUa39xkiCCpN-DMicU',
    appId: '1:565332534805:web:d07ba026638c5bcb4a501c',
    messagingSenderId: '565332534805',
    projectId: 'gac-project-b507f',
    authDomain: 'gac-project-b507f.firebaseapp.com',
    storageBucket: 'gac-project-b507f.appspot.com',
    measurementId: 'G-42B39CP74J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRFF19lx_RT1cih7HTEAFrq8s68u07iuQ',
    appId: '1:565332534805:android:c64f8431ab9c163c4a501c',
    messagingSenderId: '565332534805',
    projectId: 'gac-project-b507f',
    storageBucket: 'gac-project-b507f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF3MzRLMGxsE0NQaxgLgrQ9FYnPCSe480',
    appId: '1:565332534805:ios:a2048917689ff3f24a501c',
    messagingSenderId: '565332534805',
    projectId: 'gac-project-b507f',
    storageBucket: 'gac-project-b507f.appspot.com',
    iosBundleId: 'com.example.gac',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF3MzRLMGxsE0NQaxgLgrQ9FYnPCSe480',
    appId: '1:565332534805:ios:a2048917689ff3f24a501c',
    messagingSenderId: '565332534805',
    projectId: 'gac-project-b507f',
    storageBucket: 'gac-project-b507f.appspot.com',
    iosBundleId: 'com.example.gac',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAneAQm0vFQsTnssEUa39xkiCCpN-DMicU',
    appId: '1:565332534805:web:73c46ac35264944f4a501c',
    messagingSenderId: '565332534805',
    projectId: 'gac-project-b507f',
    authDomain: 'gac-project-b507f.firebaseapp.com',
    storageBucket: 'gac-project-b507f.appspot.com',
    measurementId: 'G-N2E6HMJ3T0',
  );
}
